// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARMbVAyyu_E03K4qfqcehGeGeJTSzMZO4',
    appId: '1:863121429958:web:de50ac521c78dc6f7f0ec7',
    messagingSenderId: '863121429958',
    projectId: 'chat-app-b0a5e',
    authDomain: 'chat-app-b0a5e.firebaseapp.com',
    storageBucket: 'chat-app-b0a5e.appspot.com',
    measurementId: 'G-EY6ZD4HQZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxSFVH3INWFynseyOyWvstzHSFntwXUQc',
    appId: '1:863121429958:android:899cadaa7be12b5f7f0ec7',
    messagingSenderId: '863121429958',
    projectId: 'chat-app-b0a5e',
    storageBucket: 'chat-app-b0a5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2IE6rQMQAs_xdilHfSJnbQoNhScfSnPM',
    appId: '1:863121429958:ios:5b24870974f1750e7f0ec7',
    messagingSenderId: '863121429958',
    projectId: 'chat-app-b0a5e',
    storageBucket: 'chat-app-b0a5e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2IE6rQMQAs_xdilHfSJnbQoNhScfSnPM',
    appId: '1:863121429958:ios:5b24870974f1750e7f0ec7',
    messagingSenderId: '863121429958',
    projectId: 'chat-app-b0a5e',
    storageBucket: 'chat-app-b0a5e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
